### ISSUE TITLE
MacOS version dialog should follow MacOS UI guidelines

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#330]
In GitLab by @Kelson42 on Nov 18, 2018, 17:37

This can probably be done by changing the UI framework from PyGTK to Qt or Electron

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Nov 18, 2018, 17:41

hum, it's a lot more than just switching framework but… some have better/easier OS integration for basic stuff like Menu bar, Preferences, etc.

Agrees we should share all OS integration issues inside this one.

**Comment by kelson42** [comment]
To me this is not really a bug because it works as designed. It is just annoying.

**Comment by rgaudin** [comment]
Electron alternative: https://tauri.studio/

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
