### ISSUE TITLE
Presets should be available through a select box

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#367]
In GitLab by @Kelson42 on Dec 12, 2018, 08:14

We have a few presets in the git and we might have a few more. To use them we have to go to the (online) git repo, download them and then load them manually. This is too complicated, we should just provide a select box in the UI which does all of that.

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
