### ISSUE TITLE
Make Kiwix logo default for Favicon, logo etc in new Hotspot installer

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#376]
In GitLab by @mrjohnc on Jan 2, 2019, 17:08

Maybe have the Kiwix logo and a Favicon, logo etc as defaults in the new installer? This would allow people to understand the file formats and sizes needed.

**Comment by mrjohnc** [comment]
> In GitLab by @mrjohnc on Jan 2, 2019, 17:08
> 
> Maybe have the Kiwix logo and a Favicon, logo etc as defaults in the new installer? This would allow people to understand the file formats and sizes needed.

Yes that sounds fine, as long as it was very easy and clear to know how to change them

**Comment by rgaudin** [comment]
done a long time ago
