### ISSUE TITLE
Check automatically that Kiwix-Hotspot start on Windows/Mac/Linux (Introduce continous integration)

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#406]
In GitLab by @Kelson42 on Jun 22, 2019, 08:15

With https://github.com/kiwix/kiwix-desktop/issues/188 we have discovered that we made 2 releases which were not starting at all on Windows. We need to find a way to secure that this never happen anymore. That is why I propose to create automated tests to check that the app starts properly. Probably this should be part of a - to be created - CI.

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
