### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#416]
In GitLab by @rgaudin on Aug 27, 2019, 15:12

In order to support the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your reader:

* is feeding itself from the OPDS stream (using a local cache/copy or not)
* is using the lastest libkiwix (not released ATM). It supports new options and includes the backward-ompatibility bits you'd need.
* is using the [centralized Categories List](https://github.com/kiwix/kiwix-tools/issues/317)
* is using the new tags only for flavours and full-text index.

**NOTE**: This issue for planning purposes, OPDS and libkiwix **does not support** those features at the moment.

**Comment by kelson42** [comment]
We should do that at the time we use OPDS.

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
