### ISSUE TITLE
Installer should not accept logo files that are not images

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#422]
In GitLab by @Popolechien on Oct 28, 2019, 09:05

Someone created a Configuration on the cardshop using a PDF file as source for the logo - it obviously did not work (see screenshot below), but the installer nonetheless accepted it and the user could not know until they downloaded, installed and accessed the hotspot. I suggest either limiting the formats acceptable to .png or .jpg or at the very least change the wording (both on the installer and cardshop to "jpg/png format only".
 
![Screenshot_20191028_093639_org.mozilla.firefox](/uploads/f5c1af05e204a7b084ef5111551e81c1/Screenshot_20191028_093639_org.mozilla.firefox.jpg)

**Comment by rgaudin** [comment]
In GitLab by @Popolechien on Oct 28, 2019, 09:15

changed the description

**Comment by rgaudin** [comment]
In GitLab by @Popolechien on Oct 28, 2019, 09:15

changed the description

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
