### ISSUE TITLE
Create Windows package

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#448]
In GitLab by @Kelson42 on Dec 5, 2019, 05:47

In one of this formats: .msix, .msixbundle, .msixupload, .appx, .appxbundle, .appxupload, .xap
This has to work with the CI.

This is necessary to be able to publish on the Microsoft App Store, see #343

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
