### ISSUE TITLE
[USABILITY] Publish the software in Apple Store

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#45]
In GitLab by @Kelson42 on Jul 6, 2017, 19:27

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 19, 2017, 15:00

macos application distributed outside of apple store is signed.

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
