### ISSUE TITLE
get app notarized by Apple

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#497]
App should be [notarized by Apple](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution) to avoid warnings and manipulations on first start on Catalina+

**Comment by kelson42** [comment]
@rgaudin I don’t want to postpone really much longer 2.4 release, but should we not do that as well?

**Comment by rgaudin** [comment]
Currently, the only thing preventing us from notarizing the app is the Etcher binary we are bundling to write images to SD-cards.

Balena abandonned etcher-cli at version 1.4.8 without reason and without responding about those reasons. It's possible it is to save their Etcher Pro market as all the competition is GUI based.

etcher-cli 1.4.8 uses `pkg` to compile its node project into a single binary.
Unfortunately, pkg produces binaries that fails to sign in strict mode: https://github.com/vercel/pkg/issues/128

This ticket is usefull in that it is still open 😅 but also references alternatives to pkg:
- nexe has similar issue https://github.com/nexe/nexe/issues/446
- http://enclosejs.com/ doesn't even install (403)
- [node-packer](https://github.com/pmq20/node-packer) is reported to sign OK but I had difficulties compiling it this way and the binary it produces is signable but not working.
- [node-packer fork](https://github.com/slee047/node-packer) binaries are hosted in a dead website

Our best option is obviously to replace etcher-cli dependency but there's no alternative in sight.
We could rely on `dd` on macOS if we'd prefer to have notarization sooner than later.

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
