### ISSUE TITLE
Something is wrong with configurations size calculation

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#610]
I am looking at https://cardshop.hotspot.kiwix.org/configurations/327 which has the following contents:
```
Nomad android app (50 MiB) 
Math Mathews android (50 MiB) 
Africatik apps (2.7 GiB) 
KA Lite fr (11.35 GiB)
cest-pas-sorcier_fr_all.fr (74.7 GiB)
jaimelire_fr.fr (70.49 MiB)
japprendsalire_fr.fr (109.45 MiB)
les-fondamentaux_fr_all.fr (126.63 MiB)
vikidia_fr_all_maxi.fr (801.7 MiB)
wikipedia_fr_all_maxi.fr (28.91 GiB)
education-et-numerique_fr_all.fr (3.52 giB)
wiktionary_fr_app_nopic.fr (1.13 GiB)
```

If I had these file sizes, I come to a rough total of 124 Gib (make it 132 GiB when adding the 8GiB default image setup). The card size is however computed to take 147,88 GiB.

If I poke around and try to build the same config from scratch, it looks like the addition of Khan Academy is the one that causes the largest discrepancy. For instance 8GiB empty card + Khan FR (11.35 GiB) = 21.65 GiB configuration (instead of 19.35 Gib)

**Comment by rgaudin** [comment]
Replicated your config and got this
<img width="360" alt="Screen Shot 2021-05-28 at 11 01 23" src="https://user-images.githubusercontent.com/57929/119974394-1c94fd00-bfa4-11eb-96cb-4940a8c5b5e7.png">

What is your concern exactly ? That the sum of all content is not equal to the total size indicated?
Please share a config.json file so that I can give you exact number about each content and what margins we add and the reasons for those.

**Comment by Popolechien** [comment]
JSON is not supported here, will send via Slack

**Comment by rgaudin** [comment]
```json
{
    "name": "Something",
    "project_name": "Some name",
    "language": "fr",
    "timezone": "Europe/Paris",
    "wifi_password": null,
    "admin_account": {
        "login": "abcdefgh",
        "password": "abcdefgh"
    },
    "size": "200 GB",
    "content": {
        "zims": [
            "cest-pas-sorcier_fr_all.fr",
            "jaimelire_fr.fr",
            "japprendsalire_fr.fr",
            "les-fondamentaux_fr_all.fr",
            "vikidia_fr_all_maxi.fr",
            "wikipedia_fr_all_maxi.fr",
            "education-et-numerique_fr_all.fr",
            "wiktionary_fr_app_nopic.fr"
        ],
        "kalite": [
            "fr"
        ],
        "wikifundi": [],
        "aflatoun": true,
        "edupi": false,
        "edupi_resources": null,
        "nomad": true,
        "mathews": true,
        "africatik": true
    },
    "branding": {
        "logo": null,
        "favicon": null,
        "css": null
    }
}
```

**Comment by kelson42** [comment]
This bug has been fixed in image-creator
