### ISSUE TITLE
Allow image creation that includes locally-stored file

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#615]
Should a user generate a zim file with zimit, they should be able to include said file (presumably locally stored) to their configuration and have it in the end image.

**Comment by kelson42** [comment]
After having discussed this with @rgaudin and @mgautierfr it seems that we should allow to do that in the CMS, and the the cardshop will just follow.

**Comment by rgaudin** [comment]
@kelson42 this is not the Cardshop, this is kiwix-hotspot. Users manually firing the hotspot tool should IMO have a relatively easy way to add non-published zim files. A bit different than cardshop use case.

**Comment by kelson42** [comment]
@rgaudin Agree

**Comment by kelson42** [comment]
Duplcate of #664 

Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
