### ISSUE TITLE
files being flagged as malicious.

### ISSUE THREAD

**Issue by TheTyPhyter** [offspot/kiwix-hotspot#619]
launcher.exe is flagged as malicious by AV and virustotal.

**Comment by rgaudin** [comment]
@TheTyPhyter thanks for the feedback. We'll look into it. Do you have a screenshot or report of those antivirus software that would help understand why it got flagged?

**Comment by kelson42** [comment]
@rgaudin I propose to close this ticket as `WONTFIX` because work on Kiwix-Desktop 3.0 (image-creator) makes good progress.

**Comment by rgaudin** [comment]
I agree. d25db9c9bb
