### ISSUE TITLE
Cache directory behaviour seems a bit implicit

### ISSUE THREAD

**Issue by kelson42** [offspot/kiwix-hotspot#623]
Following https://sourceforge.net/p/kiwix/discussion/604121/thread/380ce63aaa/#be32, I was not sure anymore about how works the cache. I thought there should be a way to specify/display it... but actually it is not. It seems that this is implicitly linked to the output directory... does that mean that if someone changes the output directory, the "old" cache is not used?

**Comment by rgaudin** [comment]
Yes, the cache is a sub-folder named `kiwix-hotspot.cache/` inside the `--build-dir`.
