### ISSUE TITLE
Integrate Datapost (or similar data collection tool)

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#627]
World Possible's Rachel has deployed a very neat tool called Datapost that allows people to connect to a box and download a set of metrics on their Android device. From there, they can carry it to the next wi-fi enabled area and upload that data so that the devices can "ping". They [uploaded a short video](https://www.youtube.com/watch?v=COt3UqdE-N8) explaining the basics.
![1589ddf1-60c9-be54-748c-09324ceacb3a](https://user-images.githubusercontent.com/21675885/144022980-3b55f794-a33b-4c96-9b32-bc18de32c661.jpg)

![07e9e2bc-5ade-44fb-5fe4-f6e2303f064e](https://user-images.githubusercontent.com/21675885/144023286-b97d52fe-b5e6-4294-8249-3b36e2f58452.jpg)

I've sent them a note asking for more info (could not find their main dev on here unfortunately)

**Comment by kelson42** [comment]
@Popolechien Similar ro #510, no?

**Comment by Popolechien** [comment]
@Kelson Ah yes. Should I update #510 listing this specific solution?

**Comment by kelson42** [comment]
@Popolechien Not necessary, both tickets will be linked.
