### ISSUE TITLE
Add hotspot installer to Balena Hub

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#629]
It is possible to promote RPi-based projects on Balena Etcher. See https://hub.balena.io/submit
![image](https://user-images.githubusercontent.com/21675885/145552811-1435505f-22d1-4716-91f4-1266c1bafc89.png)

**Comment by rgaudin** [comment]
Is this the link from the UI? If so, it's only for balena-compatible projects which we are not. Stumbled across this when researching balena already.
