### ISSUE TITLE
Creator crashes at start

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#630]
When launching https://cardshop.hotspot.kiwix.org/orders/L763R61BF I immediately got a crash with the following (and up to this day never seen) error:
```'''[19:30:39] --> Prepare Image file
Call: ['/sbin/losetup', '--find']
/dev/loop8[19:30:39] --> Change loop device mode (None)
[19:30:39] Installation failed: [Errno 2] No such file or directory: '/dev/loop8'

--- Exception Trace ---
Traceback (most recent call last):
  File "run_installation.py", line 121, in run_installation
  File "backend/mount.py", line 180, in allow_write_on
FileNotFoundError: [Errno 2] No such file or directory: '/dev/loop8'
````'''

**Comment by rgaudin** [comment]
Ah that must have been me, testing my Bard image stuff on the worker host. Please retry.

**Comment by Popolechien** [comment]
Nope. Same issue with https://cardshop.hotspot.kiwix.org/orders/L764R61BF

**Comment by rgaudin** [comment]
Sorry I didn't clean it correctly but that was the reason. Did it and re-created that last order. It's working.

**Comment by Popolechien** [comment]
Well, nope. Both https://cardshop.hotspot.kiwix.org/orders/L765R61C0 and https://cardshop.hotspot.kiwix.org/orders/L766R61C0 crashed again, again with C'est pas sorcier, around 15 and 23% of it.

**Comment by rgaudin** [comment]
This is not related to this loop-device ticket at all. Please bump the download-related ticket instead

**Comment by Popolechien** [comment]
woops my bad ^^
