### ISSUE TITLE
GUI space checker should consider content size as well

### ISSUE THREAD

**Issue by kelson42** [offspot/kiwix-hotspot#638]
And report an error otherwise

**Comment by kelson42** [comment]
See #636 for example for an idea of the user impact

**Comment by rgaudin** [comment]
It seems we are only accounting for SD card size to display the warning in GUI mode. In the example below, we want a 256G card plus 100+G of content and it only requires those 256G.

We already have a proper card size + content size check in CLI mode, that we should port to GUI.

<img width="524" alt="Screen Shot 2022-02-16 at 16 48 56" src="https://user-images.githubusercontent.com/57929/154302161-b08c0832-b3ef-4714-baa0-d59b45db4486.png">

**Comment by kelson42** [comment]
This has been implemented in image-creator.
