### ISSUE TITLE
"Kiwix Hotspot" is damaged and can't be opened on macOS

### ISSUE THREAD

**Issue by alexbirkett** [offspot/kiwix-hotspot#639]
The disk image (kiwix-hotspot-macos-2.4.11.dmg) won't open on macOS Big Sur Version 11.5.2. I've tested on M1 and Intel macs.

<img width="272" alt="Screenshot 2022-02-28 at 20 56 36" src="https://user-images.githubusercontent.com/530659/156049934-1ca6f1ca-ce01-4066-b9c4-7e2faaea3566.png">

**Comment by rgaudin** [comment]
See #497

**Comment by rgaudin** [comment]
And we don't support M1. 2.4 most likely won't support it

**Comment by rgaudin** [comment]
Workaround is to remove the quarantine on the DMG, open it and install again

```sh
sudo xattr -r -d com.apple.quarantine kiwix-hotspot-macos-2.4.11.dmg
```
