### ISSUE TITLE
Exfat-fuse error message despite being installed

### ISSUE THREAD

**Issue by alexbirkett** [offspot/kiwix-hotspot#640]
exfat-fuse, exfat-utils and udisks2 are installed yet I get a `exfat-fuse is required.` error message

[Log](https://pastebin.com/qNRNfPuk)

**Comment by rgaudin** [comment]
Thank you for the report. What distribution are you on? This is triggered when `/sbin/mount.exfat` is missing or you don't have execution rights unless you have exfat support in the kernel (visible in `/proc/filesystems`).

**Comment by rgaudin** [comment]
Sorry I just saw you mentionned Ubuntu

**Comment by rgaudin** [comment]
Can you provide output of `dpkg -l |grep exfat` ?

**Comment by samuk** [comment]
@alexbirkett This also just happened to me. It worked after a reboot though. Have you tried it since a reboot?

**Comment by kelson42** [comment]
@samuk @alexbirkett Without more information about your respective systems, we will have to close this ticket. Kiwix-hotspot should not use Fuse to mount exfat, this is weird and we need first to understand why.

**Comment by rgaudin** [comment]
> Kiwix-hotspot should not use Fuse to mount exfat, this is weird and we need first to understand why.

??? kiwix-hotspot cannot rely on some kernel module or configuration and thus is mostly dependent on exfat-fuse for regular users.

**Comment by kelson42** [comment]
@rgaudin This is within the qemu right, so we control it?

**Comment by kelson42** [comment]
@rgaudin Thx for correcting my mistake, so this kind of problem might still happen with future image-creator (assuming we stay with exfat).

**Comment by kelson42** [comment]
@rgaudin I would propose to close this ticket as `WONTFIX` because we won't rely on `exfat` anymore with the future Kiwix Hotspot 3.0 and this is too much work to fix this ticket for the few next maintenance release of Kiwix-Hotspot 2.

**Comment by rgaudin** [comment]
I agree d25db9c
