### ISSUE TITLE
Reduce range of available timezones

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#641]
The installer offers a large, very large number of possible location for timezones
(here on the desktop)
![Capture d’écran 2022-03-15 à 09 48 41](https://user-images.githubusercontent.com/21675885/158340622-ef586c29-a8ad-489e-be8f-83177fb79ede.png)
(here on the cardshop)
![Capture d’écran 2022-03-14 à 16 58 31](https://user-images.githubusercontent.com/21675885/158340640-ee09fe1d-870f-42de-9607-1a66ca80a169.png)

This is simply too many and poor UX. I remember there was a specific ask that warranted the adding of timezones, but there should be a middle ground that limits itself to CET, EST, IST, etc. (ie 25 segments already)

**Comment by rgaudin** [comment]
Agrees this is not convenient but I don't think limiting options is the way to go. There are examples of alternative ways to request this information though.

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
