### ISSUE TITLE
Add support for arbitary files

### ISSUE THREAD

**Issue by samuk** [offspot/kiwix-hotspot#643]
I've got ~4GB of PDF files as part of my [content bundle](https://archive.org/details/rosettaphone.org) (which also includes .zim and .apk files) 

Could support for arbitrary files be added? 

Perhaps A [user upload page [](](https://github.com/worldpossible/contentshell/blob/23e5c266ee79c19aa8827224812c5406e9a46920/admin/js/upload.js) similar to Rachel or Piratebox has?

If that was possible I'd have a follow-up request to include [PDF.JS ](https://mozilla.github.io/pdf.js/)so pages could be rendered on mobile devices that don't include a browser based PDF reader.

**Comment by rgaudin** [comment]
Edupi package allows you to upload and share any file. It's an old piece of software so probably no PDF.js inside but there might be a thumbnail generator. Please give it a try.
