### ISSUE TITLE
Open hardware support?

### ISSUE THREAD

**Issue by samuk** [offspot/kiwix-hotspot#645]
Is there any interest in supporting open hardware? Perhaps the [Radxa Zero ](https://wiki.radxa.com/Zero/hardware/zero)

**Comment by Popolechien** [comment]
@samuk Oh we have plenty of interest, but no developer available unfortunately. But overall and considering the current shortage having alternatives to RPi can't be a bad idea.

**Comment by kelson42** [comment]
Would be nice, but for the moment totally out of question because of lack of resources :( Maintaining the solution on all versions of RPI is already a burden.

**Comment by samuk** [comment]
OK thanks, I'll explore whether a homebrew version is viable, perhaps https://github.com/coova/coova-chilli or similar

**Comment by samuk** [comment]
Or maybe https://piratebox.cc/raspberry_pi:diy:armbian
