### ISSUE TITLE
create library for kiwix-serve

### ISSUE THREAD

**Issue by samuk** [offspot/kiwix-hotspot#646]
I'm not using your installer, so apologies if this is the wrong place to ask.

I've set up piratebox on a Orange Pi Zero as [documented here](https://github.com/Agroecology-Lab/edu-hotspot/blob/master/README.md)

I've apt install kiwix-tools

I can run a single zim with 
kiwix-serve --port=1024 myfile.zim

How can I create a library so all my .zim files are visible to users?

I tried just creating it with nano:
 ls kiwix-manage  kiwix-read  kiwix-search kiwix-serve  library.xml  wikiwel_en_all_maxi_2018-10.zim
root@orangepizero:/opt/piratebox/kiwix/kiwix-tools_linux-armhf-3.2.0-2# kiwix-manage library.xml wikiwel_en_all_maxi_2018-10.zim 
Usage:
	kiwix-manage LIBRARY_PATH add ZIM_PATH [OPTIONS]
	kiwix-manage LIBRARY_PATH remove ZIM_ID [ZIM_ID]...
	kiwix-manage LIBRARY_PATH show [ZIM_ID]...

**Comment by rgaudin** [comment]
```sh
kiwix-manage library.xml add myfile.zim
kiwix-manage library.xml add mysecondfile.zim

kiwix-serve -p 1024 --library library.xml

# alternatively, simpler:
kiwix-serve -p 1024 ./zimfolder/*.zim
```

**Comment by samuk** [comment]
Thanks
