### ISSUE TITLE
Scrambled/missing Wikifundi data after shrink

### ISSUE THREAD

**Issue by scoutg85** [offspot/kiwix-hotspot#651]
Hi, I recently made an image that includes Wikifundi. Upon clicking on Wikifundi, I get the following error page:

[a3ce[2503712086](tel:2503712086)e0dcd3692b] 2022-06-05 04:43:49: Fatal exception of type Wikimedia\Rdbms\DBQueryError

Is there a way to fix this ? I am going to re-order the image and try flashing it on an SD again.

Side notes:
The image is less than 100gb and was burned on a 256gb mini SD.

**Comment by kelson42** [comment]
@scoutg85 That would be my favourite scenario: corruped SD card or data on SD cars.

**Comment by scoutg85** [comment]
Made another image with only Wikifundi and the same error occurred. 

[a3ce2503712086e0dcd3692b] 2022-06-05 04:43:49: Fatal exception of type Wikimedia\Rdbms\DBQueryError

Any one else with the same issue?

**Comment by kelson42** [comment]
@scoutg85 What is the http request URL you made to get such an error?

**Comment by scoutg85** [comment]
Wikifundi, I have tried making an image with wiififundi selected as an
option and it's just not working.

**Comment by kelson42** [comment]
Can you post please your config file here?

**Comment by scoutg85** [comment]
Not sure if this is what you are asking for: Image Creation Task        629fd5553c58c8001ef4fd19Scheduler ID       629fd5533c58c8001ef4fcf3Order L1082R629F Config Display:                {    "admin_account": {        "login": "admin",        "password": "obiwan2007"    },    "branding": {        "css": null,        "favicon": null,        "logo": {            "fname": "logo.gif"        }    },    "content": {        "aflatoun": false,        "africatik": false,        "edupi": true,        "edupi_resources": null,        "kalite": [],        "mathews": false,        "nomad": false,        "wikifundi": [            "en"        ],        "zims": ""    },    "language": "en",    "name": "Civil Affairs CIM Cloud",    "project_name": "Civil Affairs CIM Cloud",    "size": "16 GB",    "timezone": "US/Eastern",    "wifi_password": null} Sent from Mail for Windows From: KelsonSent: Wednesday, June 8, 2022 7:18 AMTo: offspot/kiwix-hotspotCc: scoutg85; MentionSubject: Re: [offspot/kiwix-hotspot] Wikifundi Fatal Exception of Type Wikimedia (Issue #651) Can you post please your config file here?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by rgaudin** [comment]
@scoutg85 thank you for your report. I'll try to reproduce. Was this a Cardshop run?

**Comment by scoutg85** [comment]
@rgaudin yes. Kiwix support just told me via email : "the scraper crashed at 94%, I've restarted it." I will try to rebuild the image and see if it works

**Comment by Popolechien** [comment]
> the scraper crashed at 94%

This is unrelated to Wikifundi / the cardshop but relates to this zimfarm job: https://farm.openzim.org/recipes/armypubs_en_all

**Comment by scoutg85** [comment]
@Popolechien So regarding scraping, I should keep an eye on Zimfarm's status to see when it's resolved.

**Comment by Popolechien** [comment]
@scoutg85 Correct. Specifically [this job here](https://farm.openzim.org/pipeline/ce54221eea77ce417c4e0a26).

**Comment by scoutg85** [comment]
@Popolechien any idea why the Wikfundi is still not working?

**Comment by rgaudin** [comment]
@scoutg85 I am working on it and will let you know once we have a fix. I can tell you that your image is indeed not working and that wikifundi data and database are missing/truncated.

**Comment by scoutg85** [comment]
@rgaudin I appreciate the response. I thought I was doing something wrong.

**Comment by rgaudin** [comment]
Additional information:
- When flashing your image to card, I get a warning that DATA partition is corrupt.
- Ran the installer locally and didn't get the corrupt warning and WikiFundi EN works as expected.

Logs indicate that the file was properly downloaded (4GB) and was extracted but I noticed that extracting it to the mounted data partition is the last operation before unmounting said partition (given that configuration has no ZIM). My feeling is that the lack of `sync()` here have the unmount happen before data is actually wired to disk and that's how we end-up with the wikifundi *structure* but a `0b` database and no images.

I am going to add a `sync()` and test that build on the cardshop worker with the same configuration to validate this hypothesis.

**Comment by scoutg85** [comment]
> > Only difference I noted is that manual tests were not requesting a 256GB card while task was. Testing that now.

Just to clarify, it will work if the media size is smaller than 256?

**Comment by scoutg85** [comment]
I just generated an image with wikifundi and it seems to be working again (size 256gb)

**Comment by rgaudin** [comment]
Thanks for confirming. Findings lead to the culprit being in the shrinkage of non-full images that would be shrunk a bit too much.

**Comment by kelson42** [comment]
@rgaudin Considering the edge case and the fact that Kiwix-Hotspot 3.0 won't suffer of this problem, I wonder if this ticket will see a real fix coming at some point?

**Comment by rgaudin** [comment]
Probably not. Closing as per d25db9c
