### ISSUE TITLE
Add drivers for long range RPi antennas

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#653]
Orange's provider tested their Raspberry Pis over the week-end and it appears that none of the long-range antennas they added to the set up work or even are recognized.
They're asking that we add extra drivers to cover for each antenna.

**Comment by rgaudin** [comment]
Can you get the drivers or packages for those drivers ?

**Comment by kelson42** [comment]
What is the problem we try to solve here basically? Long range antenna, why not... but if the wifi client are "normal", not sure this will help.

**Comment by Popolechien** [comment]
> Can you get the drivers or packages for those drivers ?

I've sent a note to that effect.

**Comment by kelson42** [comment]
@rgaudin @Popolechien Now that we have proper limit, I guess this ticket can be closed as WONTFIX?

**Comment by rgaudin** [comment]
Yes, reported hasn't even sent feedback regarding the fix. Given the need was unclear and the amount of support it requires, this is wontfix for now.
