### ISSUE TITLE
Asks for login and password on bootup - Default Free Image for PI

### ISSUE THREAD

**Issue by FluxTux** [offspot/kiwix-hotspot#654]
I completed the online install of default (free) package for Raspberry Pi. Used imager to flash a 128 gig card, booted in Pi.

Obvious errors are FAILED to start dhcpd on all interfaces > on board and 2 x usb WIFi work using Pi OS by default

Then I am asked for login and password, which I cannot seem to find anywhere online or in forum.

THanks for help

**Comment by rgaudin** [comment]
The hotspot is mostly meant as a plug and connect via WiFi device (hence the name).
You're free to use it as you please though of course.

the dhcpd error line is normal and displays on all boots.

Use of additional network cards is not supported but you're free to tweak the system for it to work.

Credentials are the same as the raspbian it is based off:
username: pi 
password: raspberry

**Comment by Popolechien** [comment]
@FluxTux A bit more clearly: you got this prompt because you plugged your Pi onto a screen. But this will not be of any use because the only way to access the content is to connect via wifi.

**Comment by FluxTux** [comment]
Thank you for your responses
