### ISSUE TITLE
Army Pub Directory Not Working 

### ISSUE THREAD

**Issue by scoutg85** [offspot/kiwix-hotspot#656]
"Army Publishing Directorate" library was working fine up until recently; new images now doesn't allow Army Pubs to load (doesn't load on Android, iOS, or Windows).

**Comment by rgaudin** [comment]
Thanks for the report. This repo is solely about the hotspot software(s) and not the ZIM files. Issues with ZIM files should be reported on their scraper's repository which is https://github.com/openzim/zimit in this case.

As you know, zimit ZIMs quality is random as this is a generic scraper. Please open a ticket there, mentioning the version of the ZIM you are using (the YYYY-MM period in the URL) and what exactly you are getting versus what you expect.

armypub had problems in the past, most notably not working in Firefox but I just tested 2022-07 version and it works in Firefox.
