### ISSUE TITLE
Add shutdown button to homescreen

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#659]
This is a recurring demand from users wary that simply unplugging the RPi could damage it or the SD card. 

Some simple button on the landing page which, when clicked, would display a message along the lines of "it is now safe to unplug your device".

**Comment by kelson42** [comment]
It's not a good idea to my opinion because:
* we will have to build security around that to avoid normal users to click on it
* It has basically no clear value/usage
* It complexify code and UI
* It's an antipattern for an online service

**Comment by rgaudin** [comment]
Agrees with @kelson42 ; probably best addressed by documentation (won't harm sdcard) and suggestion to use a power cord with a switch on it.

There is a potential gain in clean shutdown as to not corrupt files (not hardware) on writes during shutdown but it's negligible IMO.

**Comment by Popolechien** [comment]
The power cord is an idea (did not know it existed) but at this stage I'd even be willing to live with a fake button just to put people's mind at ease. At the end of the day if users demand it, we need to find a way to accomodate them, not push some literature they won't read.

**Comment by rgaudin** [comment]
With a mission to increase education through access to information, it'd be pretty weird to support misinformation and endorse incorrect knowledge.

Not only would a _fake button_ be wrong, it would be work and maintenance. You seem to be asking for this in response to user feedback asking how to shut it down. What will you tell them when they'll start questioning why on earth are we the only Pi-user to have to shut it down and not just unplug-it ?

I think we can add a link in the emails we send to a mini FAQ on the website like “Ten things you should know before running your Pi”. If you're asked about power-off, you send the link. I believe this is the kind of info that sticks to your mind once you've learnt it.

And we should definitely recommend the button-ed power cord as this would really increase the power slot's lifespan if it is powered off frequently.
![5V-2-5A-Power-Supply-Raspberry-Pi-3-B-DC-Power-Adapter-Switch-Button-EU-US-1903631665](https://user-images.githubusercontent.com/57929/184832449-9abbdb5d-924d-4359-b01d-d809d0493da2.jpg)

I have something like this for the micro-usb ones but I don't for USB-C and I'll try to find one

**Comment by Popolechien** [comment]
found this one for USB-C https://thepihut.com/products/usb-c-cable-with-switch

**Comment by rgaudin** [comment]
Ah great ; that's just an extension !
