### ISSUE TITLE
Adding local ZIM files

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#664]
From #661, in addition to to-come OPDS library+download, having the ability to add locally stored ZIM files onto the image would be very useful.

This is different than the cache which stores the in-OPDS ZIM file which can be superseded at any moment.

**Comment by kelson42** [comment]
@rgaudin Do we plan to allow this in Kiwix Hotspot `3.0.0`? Maybe we should move the ticket somewhere else?

**Comment by Popolechien** [comment]
I reckon that enabling this possibility earlier rather than later would make sense if we want to encourage a possible integration with zimit.

**Comment by rgaudin** [comment]
For `3.0.0`, probably not but it's a good feature so for a later release, that makes sense.

We'll have to keep it here until we're at a point we have a repo for the new version (assuming we're switching repo). I dislike empty repos with issues: the process is not settled and it's hard to turn them into actionable tickets afterwards. So I'd leave them here until then.

**Comment by kelson42** [comment]
Duplicate of #664

Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
