### ISSUE TITLE
Single sudo request

### ISSUE THREAD

**Issue by rgaudin** [offspot/kiwix-hotspot#665]
From #660, due to the long-lasting nature of the process, the several calls to `sudo` on posix systems results in up to three user requests in standard GUI mode. This is not optimal.
Windows version always starts with admin requests and is thus similar to the `--root` cli option.

A possibility would be to start a different, sudo-ed process once the GUI configurations are done.

**Comment by kelson42** [comment]
@rgaudin I guess this has to be moved to `image-creator` repository?

**Comment by rgaudin** [comment]
image-creator will be a root-only process and as such this will be unnecessary for itself and will solve it for projects that integrates it.
