### ISSUE TITLE
Make it possible to rename SSID

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#672]
Use case: an image is created with the default `kiwix` SSID. The end user / partner should be able to rename it to `toto` if they so wish. This would allow for whitebranding _ex post _

**Comment by rgaudin** [comment]
kiwix-hostspot doesn't support this. All configuration is done at creation time.

In next version, this is supported as:

- Turn off Pi and remove SD card
- Insert SD card in a regular computer
- A `BOOT` volume should be visible
- A file `offspot.yaml` is present, edit it with a text editor (notepad should do)
- Update the YAML to set the SSID, according to [the doc](https://github.com/offspot/runtime-config#offspotyaml-format)

To change SSID to `toto`, the file should look like:

```yaml
---
ap:
  ssid: toto
```

⚠️ file must be valid YAML and respect the format. indentation matters (number of spaces) !!!
