### ISSUE TITLE
Unable to launch installer because SSL issue

### ISSUE THREAD

**Issue by kelson42** [offspot/kiwix-hotspot#675]
I downloaded the windows installer on the "Kiwix for Raspberry Pi" page, however when I try to run the "kiwix-hotspot-win64-2.4.12" file on my Windows 11 machine, I receive the following error:
"
Failed to execute script 'main' due to unhandled exception: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
"

Open first at https://github.com/kiwix/kiwix-desktop/issues/933

**Comment by kelson42** [comment]
@Moordok314 what is your exact version of Windows?

**Comment by rgaudin** [comment]
Confirmed on Windows 11.

<img width="422" alt="Screenshot 2023-04-18 at 10 35 46" src="https://user-images.githubusercontent.com/57929/232751960-0031da61-69be-431e-b1d6-f1faa5e87095.png">

@Moordok314, we won't be releasing a fixed version very soon so you'll have to defer to this hack:

- open windows menu and type `environ` 
<img width="794" alt="Screenshot 2023-04-18 at 10 58 36" src="https://user-images.githubusercontent.com/57929/232757192-78465634-89cc-4804-85de-2208c0421fee.png">



- Open the *Edit the system environment variables* app
- Click the *Environment Variables* button at the bottom of the window
- Click the *New* button on the upper pane
- Type (**exactly**) `CRYPTOGRAPHY_OPENSSL_NO_LEGACY` as *Variable Name*
- Type `1` as *Variable value` and hit *OK*. Your window should look like:

<img width="622" alt="Screenshot 2023-04-18 at 10 57 11" src="https://user-images.githubusercontent.com/57929/232756837-60599fa3-0244-43ff-8b42-44225df99356.png">

Close the other window with *OK*. You can now launch kiwix-hotspot.
