### ISSUE TITLE
I can´t execute in W10 Pro 1909 18363.1256

### ISSUE THREAD

**Issue by runikk** [offspot/kiwix-hotspot#678]
Hi, 

I tried to execute the .exe version 2.4.12 downloaded from the following link: https://www.kiwix.org/en/documentation/how-to-set-up-kiwix-hotspot/  in 3 different computers with aproximately the same SSL error in all of them:

![SSL ERROR KIWIX](https://github.com/offspot/kiwix-hotspot/assets/70091036/a5aae800-9430-49e6-b558-9638df9a03c5)

I don´t know what is happening. I also tried Debian in Virtualbox and at 50% aprox a SSH error with connection appears and a message of "error installation".

**Comment by rgaudin** [comment]
Duplicate of #675. Can you try the workaround described there ?

**Comment by runikk** [comment]
Done! #675. SSL solved but... now I have a different error
![UTF8 KIWIX](https://github.com/offspot/kiwix-hotspot/assets/70091036/9a86205a-44cd-492f-8d32-c31a446a7d23)

**Comment by rgaudin** [comment]
Ah! We are indeed trying to decode UTF-8 while reading the output of a Windows tool that lists the disk drives. Output is thus system-encoded and I suppose it can fail if any drive have a caption that is not overlapping.

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
