### ISSUE TITLE
Too many users connect their HDMI device to the RPI and are puzzle what to do next

### ISSUE THREAD

**Issue by kelson42** [offspot/kiwix-hotspot#683]
We should probably display some kind of hint or explanation to help them move to WiFi.

**Comment by rgaudin** [comment]
Right ; we should probably create a similar ticket at base image

**Comment by kelson42** [comment]
@rgaudin OK to me, to just move it there.

**Comment by kelson42** [comment]
Duplicate of https://github.com/offspot/base-image/issues/51
