### ISSUE TITLE
Hotspot installer isn't working

### ISSUE THREAD

**Issue by LuxStatera** [offspot/kiwix-hotspot#688]
I am trying to use the hotspot installer to build an image for my raspberry pi. When I click the "static content" to access the content catalog, it fails. It says "Catalogs Download Failed" and says I should check my internet connection and/or proxy settings. I tried the installer on macos and linux but both were unable to open the content catalog. Also it seems the windows version is not longer available. How do I solve this?

**Comment by rgaudin** [comment]
@LuxStatera thank you for the report. This looks like #677 where I see you already commented.
Can you tried to access that link I mentioned in your web browser? What country are you located in?

**Comment by rgaudin** [comment]
Please respond in #677 as this is a duplicate
