### ISSUE TITLE
Footer is not located at foot of page

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#692]
By footer I mean the orange bar that's at the bottom (or halfway through my screen if I don't have this many cards.

![Capture d’écran 2024-01-31 à 14 48 59](https://github.com/offspot/kiwix-hotspot/assets/21675885/220ec356-a432-4017-a84f-eda0827f6674)

**Comment by rgaudin** [comment]
Regards obsolete UI (pending https://github.com/offspot/package-requests/issues/35)
