### ISSUE TITLE
Multiple languages stick out of cards

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#693]
Here on screenshot we can see that the language elements stretch way beyond screen.

![Capture d’écran 2024-01-31 à 14 45 56](https://github.com/offspot/kiwix-hotspot/assets/21675885/782b5d01-f03c-4752-afaa-778312bc1d6b)

**Comment by rgaudin** [comment]
Regards obsolete UI (pending https://github.com/offspot/package-requests/issues/35)
