### ISSUE TITLE
Limit visible description field to 150 characters

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#695]
As described in #694 if we want the full card to be clickable then we probably do not want an elevator to scroll through long descriptions. 
Should limit display of description to first 150 characters (and then add `...`) 

![Capture d’écran 2024-01-31 à 14 55 20](https://github.com/offspot/kiwix-hotspot/assets/21675885/527b011c-28c0-41e7-b23e-bbbf2badef44)

**Comment by rgaudin** [comment]
Regards obsolete UI (pending https://github.com/offspot/package-requests/issues/35)

**Comment by kelson42** [comment]
I would consider putting same limits as for ZIM metadata?
