### ISSUE TITLE
The url "/content/wikipedia_en_all" was not found on this server

### ISSUE THREAD

**Issue by imclerran** [offspot/kiwix-hotspot#699]
I downloaded and flashed an image from the online custom image creation tool within the last week. After connecting to the hotspot, each of the requested zim files show up on the kiwix landing page, however, when I attempt to access *any* of them, the server returns a url not found error.

**Comment by rgaudin** [comment]
@imclerran, sorry about that. That's a bug that was [introduced on Saturday](https://github.com/offspot/imager-service/commit/6421563264df5d0f88b9920ddac9e6c81b470653) and [fixed on Wednesday](https://github.com/offspot/imager-service/commit/19bc9abd31b206dad3c4aa50f079a93c579dd756).

I believe you created your card in-between those dates. Please re-order your config.
