### ISSUE TITLE
Using different device to use kiwix image on

### ISSUE THREAD

**Issue by Rancho-rachit** [offspot/kiwix-hotspot#700]
I'm willing to contribute to build the *Hotspot Companion* mobile app.
But, I don't have a Raspberry Pi.

So what are the *other ways* by which I can use the kiwix-hotspot using the image file?

These are my random guesses -
1. Using an old laptop, and go with the Virtual Box
2. convert my old mobile, to act as a raspberry pi

:+1:

**Comment by rgaudin** [comment]
kiwix-hotspot only targets Raspberry Pis for now.

- You can run its images using Qemu (even via [dockerpi](https://github.com/lukechilds/dockerpi)).
- Running this images isn't required at this stage and should not prevent you from writing a proposal not prototyping.
- Depending on th selected design, a RaspberryPi might not be needed to develop the Companion ; at least until far in the process.
