### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by jpalcantara** [offspot/kiwix-hotspot#702]
Hello,

  I am interested in the project and I am looking to see if the Raspberry PI version is enough to run the image on it.  It is the version that before Pi 3b.

Thanks

**Comment by rgaudin** [comment]
@jpalcantara this version works  from Pi0 to Pi400 AFAIK. Note that this project is not receiving any upgrade though.
Our [new project](https://github.com/offspot/overview) (not a replacement per say) targets only 64b version so Pi0/1/2 are not supported
